services:
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - JELLYFIN_PublishedServerUrl=http://10.1.10.140:8096
    ports:
      - "8096:8096"
      - "8920:8920"
    volumes:
      - /srv/jellyfin/config:/config
      - /srv/jellyfin/cache:/cache
      - /srv/jellyfin/media:/media
      - /srv/audiobookshelf/audiobooks:/audiobooks
      - /srv/audiobookshelf/podcasts:/podcasts
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - "44"
      - "990"
    restart: unless-stopped
