services:
  samba:
    image: dperson/samba:latest
    container_name: audiobooks-share
    restart: unless-stopped
    ports:
      - "139:139"
      - "445:445"
    volumes:
      - /srv/audiobookshelf/audiobooks:/mount_audiobooks
      - /srv/audiobookshelf/books:/mount_books
    env_file:
      - .env
    command:
      - -u
      - ${SAMBA_USER};${SAMBA_PASSWORD}
      - -s
      - Audiobooks;/mount_audiobooks;yes;no;no;${SAMBA_USER}
      - -s
      - Books;/mount_books;yes;no;no;${SAMBA_USER}
      - -p
